variables:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

.only-default: &only-default
  only:
    - merge_requests

stages:
  - linting
  - build
  - test
  - deploy

# LINTING

code format:
  <<: *only-default
  tags:
    - docker
  image: alpine:3.12
  stage: linting
  needs: []
  script:
    - apk add clang python3
    - clang-format --version
    - python3 ./tools/run-clang-format.py -j 1 -r --exclude tests/doctest.h src tests examples

static linting:
  <<: *only-default
  tags:
    - docker
  image: ubuntu:18.04
  stage: linting
  needs: []
  script:
    - apt update
    - apt install -y cmake g++ clang ninja-build clang-tidy
    - mkdir build && cd build
    - cmake -G "Ninja" ../ -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTCS_ENABLE_TESTS=ON -DTCS_ENABLE_EXAMPLES=ON
    - clang-tidy ../src/*.c ../examples/*.c

header updated:
  <<: *only-default
  tags:
    - docker
  image: amd64/alpine:3.12
  stage: linting
  needs: []
  script:
    - apk add m4
    - ./tools/is_header_up_to_date.sh

# COVERAGE

posix coverage:
  <<: *only-default
  tags:
    - docker
  image: amd64/alpine:3.12
  stage: linting
  needs: []
  script:
    - apk add cmake g++ ninja m4 gcovr
    - ./tools/coverage.sh
  artifacts:
    expire_in: 7 days
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./cobertura.xml

# BUILDS

win-1809 msvc v19.26:
  <<: *only-default
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: build
  needs: []
  script:
    - '& ./tools/build_msvc.bat'
    - 'mkdir build'
    - 'mv build32/tests/Debug/tests.exe ./build/tests_msvc_debug_x86.exe'
    - 'mv build32/tests/Release/tests.exe ./build/tests_msvc_release_x86.exe'
    - 'mv build64/tests/Debug/tests.exe ./build/tests_msvc_debug_x86-64.exe'
    - 'mv build64/tests/Release/tests.exe ./build/tests_msvc_release_x86-64.exe'
    - 'mv build32/tests/Debug/tests_header_only.exe ./build/tests_header_only_msvc_debug_x86.exe'
    - 'mv build32/tests/Release/tests_header_only.exe ./build/tests_header_only_msvc_release_x86.exe'
    - 'mv build64/tests/Debug/tests_header_only.exe ./build/tests_header_only_msvc_debug_x86-64.exe'
    - 'mv build64/tests/Release/tests_header_only.exe ./build/tests_header_only_msvc_release_x86-64.exe'
  artifacts:
    paths:
      - ./build/tests_msvc_debug_x86.exe
      - ./build/tests_msvc_release_x86.exe
      - ./build/tests_msvc_debug_x86-64.exe
      - ./build/tests_msvc_release_x86-64.exe
      - ./build/tests_header_only_msvc_debug_x86.exe
      - ./build/tests_header_only_msvc_release_x86.exe
      - ./build/tests_header_only_msvc_debug_x86-64.exe
      - ./build/tests_header_only_msvc_release_x86-64.exe

linux gcc v9.3 x86-64:
  <<: *only-default
  tags:
    - docker
  image: amd64/alpine:3.12
  stage: build
  needs: []
  script:
    - apk add cmake g++ ninja m4
    - mkdir build && cd build
    - cmake -G "Ninja" ../ -DCMAKE_VERBOSE_MAKEFILE=ON -DTCS_ENABLE_TESTS=ON -DTCS_ENABLE_EXAMPLES=ON -DTCS_WARNINGS_AS_ERRORS=ON
    - cmake --build .
    - mv ./tests/tests ./tests_linux_gcc_x86-64
    - mv ./tests/tests_header_only ./tests_header_only_linux_gcc_x86-64
  artifacts:
    paths:
      - ./build/tests_linux_gcc_x86-64
      - ./build/tests_header_only_linux_gcc_x86-64

linux gcc v9.3 x86:
  <<: *only-default
  image: i386/alpine:3.12
  stage: build
  needs: []
  tags:
    - docker
  script:
    - apk add cmake g++ ninja m4
    - mkdir build && cd build
    - cmake -G "Ninja" ../ -DCMAKE_VERBOSE_MAKEFILE=ON -DTCS_ENABLE_TESTS=ON -DTCS_ENABLE_EXAMPLES=ON -DTCS_WARNINGS_AS_ERRORS=ON
    - cmake --build .
    - mv ./tests/tests ./tests_linux_gcc_x86
    - mv ./tests/tests_header_only ./tests_header_only_linux_gcc_x86
  artifacts:
    paths:
      - ./build/tests_linux_gcc_x86
      - ./build/tests_header_only_linux_gcc_x86

linux mingw-w64 x86-64 winxp:
  <<: *only-default
  image: amd64/alpine:3.12
  stage: build
  needs: []
  tags:
    - docker
  script:
    - apk add cmake mingw-w64-gcc ninja m4
    - mkdir build && cd build
    - cmake -G "Ninja" ../ -DCMAKE_TOOLCHAIN_FILE="../toolchain_mingw_x86-64_winxp.cmake" -DCMAKE_VERBOSE_MAKEFILE=ON -DTCS_ENABLE_TESTS=ON -DTCS_ENABLE_EXAMPLES=ON -DTCS_WARNINGS_AS_ERRORS=ON
    - cmake --build .
    - mv ./tests/tests.exe ./tests_mingw_x86-64_winxp.exe
    - mv ./tests/tests_header_only.exe ./tests_header_only_mingw_x86-64_winxp.exe
  artifacts:
    paths:
      - ./build/tests_mingw_x86-64_winxp.exe
      - ./build/tests_header_only_mingw_x86-64_winxp.exe

linux mingw-w64 x86 winxp:
  <<: *only-default
  image: i386/alpine:3.12
  stage: build
  needs: []
  tags:
    - docker
  script:
    - apk add cmake mingw-w64-gcc ninja m4
    - mkdir build && cd build
    - cmake -G "Ninja" ../ -DCMAKE_TOOLCHAIN_FILE="../toolchain_mingw_x86_winxp.cmake" -DCMAKE_VERBOSE_MAKEFILE=ON -DTCS_ENABLE_TESTS=ON -DTCS_ENABLE_EXAMPLES=ON -DTCS_WARNINGS_AS_ERRORS=ON
    - cmake --build .
    - mv ./tests/tests.exe ./tests_mingw_x86_winxp.exe
    - mv ./tests/tests_header_only.exe ./tests_header_only_mingw_x86_winxp.exe
  artifacts:
    paths:
      - ./build/tests_mingw_x86_winxp.exe
      - ./build/tests_header_only_mingw_x86_winxp.exe

linux mingw-w64 x86-64 winblue:
  <<: *only-default
  image: amd64/alpine:3.12
  stage: build
  needs: []
  tags:
    - docker
  script:
    - apk add cmake mingw-w64-gcc ninja m4
    - mkdir build && cd build
    - cmake -G "Ninja" ../ -DCMAKE_TOOLCHAIN_FILE="../toolchain_mingw_x86-64_winblue.cmake" -DCMAKE_VERBOSE_MAKEFILE=ON -DTCS_ENABLE_TESTS=ON -DTCS_ENABLE_EXAMPLES=ON -DTCS_WARNINGS_AS_ERRORS=ON
    - cmake --build .
    - mv ./tests/tests.exe ./tests_mingw_x86-64_winblue.exe
    - mv ./tests/tests_header_only.exe ./tests_header_only_mingw_x86-64_winblue.exe
  artifacts:
    paths:
      - ./build/tests_mingw_x86-64_winblue.exe
      - ./build/tests_header_only_mingw_x86-64_winblue.exe

linux mingw-w64 x86 winblue:
  <<: *only-default
  image: i386/alpine:3.12
  stage: build
  needs: []
  tags:
    - docker
  script:
    - apk add cmake mingw-w64-gcc ninja m4
    - mkdir build && cd build
    - cmake -G "Ninja" ../ -DCMAKE_TOOLCHAIN_FILE="../toolchain_mingw_x86_winblue.cmake" -DCMAKE_VERBOSE_MAKEFILE=ON -DTCS_ENABLE_TESTS=ON -DTCS_ENABLE_EXAMPLES=ON -DTCS_WARNINGS_AS_ERRORS=ON
    - cmake --build .
    - mv ./tests/tests.exe ./tests_mingw_x86_winblue.exe
    - mv ./tests/tests_header_only.exe ./tests_header_only_mingw_x86_winblue.exe
  artifacts:
    paths:
      - ./build/tests_mingw_x86_winblue.exe
      - ./build/tests_header_only_mingw_x86_winblue.exe

# TESTS

win-1809 tests:
  <<: *only-default
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: test
  needs:
    - "win-1809 msvc v19.26"
    - "linux mingw-w64 x86-64 winxp"
    - "linux mingw-w64 x86 winxp"
    - "linux mingw-w64 x86-64 winblue"
    - "linux mingw-w64 x86 winblue"
  script:
    - ./build/tests_msvc_debug_x86.exe --reporters=junit,conosle --out=./report_win-1809_msvc_debug_x86.xml
    - ./build/tests_msvc_release_x86.exe --reporters=junit,conosle --out=./report_win-1809_msvc_release_x86.xml
    - ./build/tests_msvc_debug_x86-64.exe --reporters=junit,conosle --out=./report_win-1809_msvc_debug_x86-64.xml
    - ./build/tests_msvc_release_x86-64.exe --reporters=junit,conosle --out=./report_win-1809_msvc_release_x86-64.xml
    - ./build/tests_mingw_x86_winxp.exe --reporters=junit,conosle --out=./report_mingw_x86_winxp.xml
    - ./build/tests_mingw_x86-64_winxp.exe --reporters=junit,conosle --out=./report_mingw_x86-64_winxp.xml
    - ./build/tests_mingw_x86_winblue.exe --reporters=junit,conosle --out=./report_mingw_x86_winblue.xml
    - ./build/tests_mingw_x86-64_winblue.exe --reporters=junit,conosle --out=./report_mingw_x86-64_winblue.xml
    - ./build/tests_header_only_msvc_debug_x86.exe --reporters=junit,conosle --out=./report_header_only_win-1809_msvc_debug_x86.xml
    - ./build/tests_header_only_msvc_release_x86.exe --reporters=junit,conosle --out=./report_header_only_win-1809_msvc_release_x86.xml
    - ./build/tests_header_only_msvc_debug_x86-64.exe --reporters=junit,conosle --out=./report_header_only_win-1809_msvc_debug_x86-64.xml
    - ./build/tests_header_only_msvc_release_x86-64.exe --reporters=junit,conosle --out=./report_header_only_win-1809_msvc_release_x86-64.xml
    - ./build/tests_header_only_mingw_x86_winxp.exe --reporters=junit,conosle --out=./report_header_only_mingw_x86_winxp.xml
    - ./build/tests_header_only_mingw_x86-64_winxp.exe --reporters=junit,conosle --out=./report_header_only_mingw_x86-64_winxp.xml
    - ./build/tests_header_only_mingw_x86_winblue.exe --reporters=junit,conosle --out=./report_header_only_mingw_x86_winblue.xml
    - ./build/tests_header_only_mingw_x86-64_winblue.exe --reporters=junit,conosle --out=./report_header_only_mingw_x86-64_winblue.xml
  artifacts:
    reports:
      junit:
        - report_win-1809_msvc_debug_x86.xml
        - report_win-1809_msvc_release_x86.xml
        - report_win-1809_msvc_debug_x86-64.xml
        - report_win-1809_msvc_release_x86-64.xml
        - report_mingw_x86_winxp.xml
        - report_mingw_x86-64_winxp.xml
        - report_mingw_x86_winblue.xml
        - report_mingw_x86-64_winblue.xml
        - report_header_only_win-1809_msvc_debug_x86.xml
        - report_header_only_win-1809_msvc_release_x86.xml
        - report_header_only_win-1809_msvc_debug_x86-64.xml
        - report_header_only_win-1809_msvc_release_x86-64.xml
        - report_header_only_mingw_x86_winxp.xml
        - report_header_only_mingw_x86-64_winxp.xml
        - report_header_only_mingw_x86_winblue.xml
        - report_header_only_mingw_x86-64_winblue.xml

winxp tests x86:
  <<: *only-default
  tags:
    - andromeda
    - windows-xp
  stage: test
  needs: ["win-1809 msvc v19.26"]
  script:
    - ./build/tests_msvc_release_x86 --reporters=junit,conosle --out=./report_winxp_msvc_x86.xml
    - ./build/tests_header_only_msvc_release_x86 --reporters=junit,conosle --out=./report_header_only_winxp_msvc_x86.xml
  artifacts:
    reports:
      junit:
        - report_winxp_msvc_x86.xml
        - report_header_only_winxp_msvc_x86.xml
  allow_failure: true

linux test x86-64:
  <<: *only-default
  tags:
    - docker
  image: amd64/alpine:3.12
  stage: test
  needs: ["linux gcc v9.3 x86-64"]
  script:
    - apk add libstdc++
    - ./build/tests_linux_gcc_x86-64 --reporters=junit,conosle --out=./report_linux_gcc_x86.xml
    - ./build/tests_header_only_linux_gcc_x86-64 --reporters=junit,conosle --out=./report_header_only_linux_gcc_x86.xml
  artifacts:
    reports:
      junit:
        - report_linux_gcc_x86-64.xml
        - report_header_only_linux_gcc_x86-64.xml

linux test x86:
  <<: *only-default
  tags:
    - docker
  image: i386/alpine:3.12
  stage: test
  needs: ["linux gcc v9.3 x86"]
  script:
    - apk add libstdc++
    - ./build/tests_linux_gcc_x86 --reporters=junit,conosle --out=./report_linux_gcc_x86.xml
    - ./build/tests_header_only_linux_gcc_x86 --reporters=junit,conosle --out=./report_header_only_linux_gcc_x86.xml
  artifacts:
    reports:
      junit:
        - report_linux_gcc_x86.xml
        - report_header_only_linux_gcc_x86.xml

# DEPLOY

sphinx:
  <<: *only-default
  tags:
    - docker
  image: ubuntu:22.04
  stage: deploy
  needs: []
  script:
    - apt update
    - apt install -y python3-pip make doxygen
    - pip3 install -r docs/requirements.txt
    - cd docs
    - make html
