variables:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

.unit_tests:
  script:
    - apk add cmake g++ ninja
    - mkdir build && cd build && cmake -G "Ninja" ../
    - ninja -v
    - ./tests/tests

Unit Tests x64:
  extends: .unit_tests
  image: amd64/alpine:3.9

Unit Tests i386:
  extends: .unit_tests
  image: i386/alpine:3.9

Code Format:
  image: alpine:3.9
  script:
    - apk add clang python3
    - python3 ./tests/run-clang-format.py -j 1 -r --exclude tests/doctest.h src tests examples
